# Generated by tools/generate.py. Chunks at distance 1.
execute if score #budget chunkrand matches 1.. run function chunkrand:scan/try {dx:-1,dz:0}
execute if score #budget chunkrand matches 1.. run function chunkrand:scan/try {dx:0,dz:-1}
execute if score #budget chunkrand matches 1.. run function chunkrand:scan/try {dx:0,dz:1}
execute if score #budget chunkrand matches 1.. run function chunkrand:scan/try {dx:1,dz:0}
