#!/usr/bin/env python3
"""Regenerates the generated parts of the Chunk Randomizer datapack.

Run from the repository root:  python3 tools/generate.py

Generated files:
  data/chunkrand/tags/block/replaceable.json
  data/chunkrand/tags/block/replaceable_near_structure.json
  data/chunkrand/function/chunk/fill.mcfunction

tools/all_blocks.txt is the list of every vanilla block id. Update it when a
new Minecraft version adds blocks, then rerun this script.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data" / "chunkrand"

# Vertical range that gets filled. Slabs outside a dimension's build height
# simply fail, so this covers the overworld, nether, end and most custom
# dimensions without needing to know their heights.
MIN_Y, MAX_Y, SLAB = -64, 320, 16

# Never replaced anywhere: air stays air, and portals stay usable.
NEVER_REPLACE = {
    "air", "cave_air", "void_air",
    "end_portal", "end_gateway", "nether_portal",
}

# Kept intact in chunks near a stronghold or nether fortress.
STRONGHOLD_BLOCKS = {
    "stone_bricks", "mossy_stone_bricks", "cracked_stone_bricks", "chiseled_stone_bricks",
    "infested_stone_bricks", "infested_mossy_stone_bricks",
    "infested_cracked_stone_bricks", "infested_chiseled_stone_bricks",
    "stone_brick_stairs", "stone_brick_slab", "smooth_stone_slab", "stone_slab",
    "cobblestone", "cobblestone_stairs", "cobblestone_slab",
    "iron_bars", "iron_door", "oak_door", "oak_planks", "oak_fence", "oak_slab",
    "ladder", "torch", "wall_torch", "bookshelf", "cobweb", "chest", "spawner",
    "end_portal_frame", "stone_button", "stone_pressure_plate",
}
FORTRESS_BLOCKS = {
    "nether_bricks", "nether_brick_fence", "nether_brick_stairs", "nether_brick_slab",
    "nether_wart", "soul_sand", "chest", "spawner",
}


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def tag(ids) -> str:
    # "required": false keeps the tag loading on versions missing some blocks.
    values = [{"id": f"minecraft:{b}", "required": False} for b in sorted(ids)]
    return json.dumps({"replace": False, "values": values}, indent=2) + "\n"


def main() -> None:
    all_blocks = [l.strip() for l in (ROOT / "tools" / "all_blocks.txt").read_text().splitlines() if l.strip()]

    replaceable = set(all_blocks) - NEVER_REPLACE
    write(DATA / "tags" / "block" / "replaceable.json", tag(replaceable))
    write(DATA / "tags" / "block" / "replaceable_near_structure.json",
          tag(replaceable - STRONGHOLD_BLOCKS - FORTRESS_BLOCKS))

    fill = [
        "# Generated by tools/generate.py. Fills the chunk in 16-block-tall slabs;",
        "# slabs outside the dimension's build height fail harmlessly.",
    ]
    for y in range(MIN_Y, MAX_Y, SLAB):
        fill.append(f"$fill $(bx) {y} $(bz) $(bx2) {y + SLAB - 1} $(bz2) $(block) replace #chunkrand:$(filter)")
    write(DATA / "function" / "chunk" / "fill.mcfunction", "\n".join(fill) + "\n")


if __name__ == "__main__":
    main()
